name: Release Helm Chart
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.0'
          
      - name: Helm lint
        run: helm lint .
      
      - name: Extract chart version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "checking if tag version '$VERSION' matches helm chart"
          CHART_VERSION=$(helm show chart . | grep -E "^version:" | awk '{print $2}')
          if [[ $CHART_VERSION != $VERSION ]]; then 
            echo "Error: Chart Version: $CHART_VERSION doesn't match Release Version: $VERSION!"
            exit 1
          fi
          if docker manifest inspect ghcr.io/${{ github.repository }}:$VERSION > /dev/null 2>&1; then
            echo "Error: version already exists in registry"
            exit 1
          fi
          
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        shell: bash
      
      - name: Package Helm chart
        run: |
          helm dependency update
          helm package . --version ${{ steps.version.outputs.VERSION }} --destination .
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nifi-chart
          path: ./nifi-${{ steps.version.outputs.VERSION }}.tgz
  
  deploy:
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: nifi-chart
          path: .chart
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
                    
      - name: Push charts to GHCR
        run: |
          for pkg in .chart/*.tgz; do
            if [ -f "$pkg" ]; then
              echo "Pushing ${pkg} to OCI registry $(oci://ghcr.io/${{ github.repository_owner }})"
              helm push "${pkg}" "oci://ghcr.io/${{ github.repository_owner }}"
            fi
          done