name: Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  example:
    name: Minikube installation - Basic test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.15.0
        with:
          minikube version: 'v1.38.0'
          kubernetes version: 'v1.28.1'
          github token: ${{ secrets.GITHUB_TOKEN }}   
      #- run: minikube addons list
      #- name: Interact with the cluster
      #  run: kubectl get nodes
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: charts/nifi
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add dysnix https://dysnix.github.io/charts/
          helm repo update
          helm dep up
      - name: Install Nifi
        working-directory: charts/nifi
        run: helm install nifi .
      - name: Check deployment status
        run: |
          kubectl rollout status --watch statefulset/nifi --timeout=5m
      - name: Wait for NiFi web server to start
        run: |
          for n in [ 0 1 2 3 4 5 6 7 8 9 ]
          do
            if kubectl logs pod/nifi-0 -c app-log | grep -E "JettyServer(\b Nifi\b)? Started Server"
            then
              exit 0
            fi
            sleep 30
          done
          kubectl logs pod/nifi-0 -c app-log
          echo NiFi did not start for 300 seconds!
          exit 1
